apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cli-manager?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
     event == "push" && target_branch == "main" && 
      (".tekton/cli-manager-push.yaml".pathChanged() || 
      ".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      "api/***".pathChanged() || 
      "cmd/***".pathChanged() || 
      "dependencymagnet/***".pathChanged() || 
      "pkg/***".pathChanged() || 
      "vendor/***".pathChanged() || 
      "Dockerfile".pathChanged() || 
      "Makefile".pathChanged())
  labels:
    appstudio.openshift.io/application: cli-manager-operator
    appstudio.openshift.io/component: cli-manager
    pipelines.appstudio.openshift.io/type: build
  name: cli-manager-on-push
  namespace: clio-wrklds-pipeline-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/clio-wrklds-pipeline-tenant/cli-manager-operator/cli-manager:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
